# -*- coding: utf-8 -*-
"""Electricity Bill Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ykXo999cdO00hYlmMyA_5vNekLmrIN6Q
"""

# Electricity Bill Calculator

current_meter_reading = int(input("Enter the current meter reading: "))
previous_meter_reading = int(input("Enter the previous meter reading: "))
fixed_charges = int(input("Enter the fixed charges: "))
subsidies = int(input("Enter the subsidies: "))

if current_meter_reading < previous_meter_reading:
    print("Invalid meter readings")

else:
    units_consumed = current_meter_reading - previous_meter_reading

    if units_consumed <= 100:
        RateA = 5.50
        RateB = 0
        energy_charge = units_consumed * RateA

    else:
        RateA = 5.50
        RateB = 6.00
        energy_charge = 100 * RateA + (units_consumed - 100) * RateB

    if units_consumed > 300:
        print("Warning: High electricity usage")

    Taxes = energy_charge * 0.08

    total_bill = energy_charge + fixed_charges + Taxes - subsidies

    print("\n----- BILL SUMMARY -----")
    print("Units Consumed:", units_consumed)
    print("Rate A:", RateA)

    if units_consumed > 100:
        print("Rate B:", RateB)

    print("Energy Charge:", energy_charge)
    print("Taxes:", Taxes)
    print("Fixed Charges:", fixed_charges)
    print("Subsidies:", subsidies)

    print(f"Total Bill: ₹{total_bill:.2f}")