# -*- coding: utf-8 -*-
"""Ohm's Law Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ykXo999cdO00hYlmMyA_5vNekLmrIN6Q
"""

# Ohm's Law Calculator

print("1. Voltage = Current × Resistance")
print("2. Resistance = Voltage ÷ Current")
print("3. Current = Voltage ÷ Resistance")

choice = int(input("Choose an option (1-3): "))

if choice == 1:
    current = float(input("Enter current (A): "))
    resistance = float(input("Enter resistance (Ω): "))

    if current == 0 or resistance == 0:
        print("Invalid input")

    else:
        voltage = current * resistance
        print("\n----- RESULT -----")
        print(f"Voltage: {voltage:.2f} V")

elif choice == 2:
    voltage = float(input("Enter voltage (V): "))
    current = float(input("Enter current (A): "))

    if current == 0:
        print("Current cannot be zero")

    else:
        resistance = voltage / current
        print("\n----- RESULT -----")
        print(f"Resistance: {resistance:.2f} Ω")

elif choice == 3:
    voltage = float(input("Enter voltage (V): "))
    resistance = float(input("Enter resistance (Ω): "))

    if resistance == 0:
        print("Resistance cannot be zero")

    else:
        current = voltage / resistance
        print("\n----- RESULT -----")
        print(f"Current: {current:.2f} A")

else:
    print("Invalid choice")