# -*- coding: utf-8 -*-
"""Power Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ykXo999cdO00hYlmMyA_5vNekLmrIN6Q
"""

# Power Calculator

print("1. Current and Voltage given")
print("2. Power and Current given")
print("3. Voltage and Power given")

i = int(input("Choose an option: "))

if i == 1:
    current = float(input("Enter the current (A): "))
    voltage = float(input("Enter the voltage (V): "))

    if current == 0 or voltage == 0:
        print("Current and voltage cannot be zero")
    else:
        power = current * voltage
        print("\n----- RESULT -----")
        print(f"Power: {power:.2f} W")

elif i == 2:
    power = float(input("Enter the power (W): "))
    current = float(input("Enter the current (A): "))

    if current == 0:
        print("Current cannot be zero")
    else:
        voltage = power / current
        print("\n----- RESULT -----")
        print(f"Voltage: {voltage:.2f} V")

elif i == 3:
    voltage = float(input("Enter the voltage (V): "))
    power = float(input("Enter the power (W): "))

    if voltage == 0:
        print("Voltage cannot be zero")
    else:
        current = power / voltage
        print("\n----- RESULT -----")
        print(f"Current: {current:.2f} A")

else:
    print("Invalid choice")